---
- name: Base | Upgrade apt-packages
  sudo: yes
  apt:
    upgrade: safe
    force: yes
    update_cache: yes
    cache_valid_time: 3600
  when: apt.upgrade_packages == "safe"

- name: Base | Upgrade apt-packages
  sudo: yes
  apt:
    upgrade: full
    force: yes
    update_cache: yes
    cache_valid_time: 3600
  when: apt.upgrade_packages == "full"

- name: Base | Install System Packages
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items: apt.sys_packages

- name: Base | Configure the timezone
  sudo: yes
  template:
    src: timezone.tpl
    dest: /etc/timezone

- name: Base | More timezone configuration
  sudo: yes
  file:
    src: "/usr/share/zoneinfo/{{ base.timezone }}"
    dest: /etc/localtime
    state: link
    force: yes
    backup: yes

- name: Base | Set default system language pack
  locale_gen:
    name: "{{ base.locale }}"
    state: present
  sudo: yes

- name: Base | Set VIM as default editor
  command: update-alternatives --set editor /usr/bin/vim.basic

- name: Base | Installing cachefilesd
  sudo: yes
  apt:
    pkg: cachefilesd
    update_cache: yes
    cache_valid_time: 3600
  when: base.cachefilesd

- name: Base | Enable cachefilesd
  sudo: true
  template:
    src: cachefilesd.tpl
    dest: /etc/default/cachefilesd
  when: base.cachefilesd

- include: swap.yml
  when: base.swap