---

# todo Use a variable to force swap (re)creation

- name: Swap | Create swap file
  command: "dd if=/dev/zero of={{ swap.file_path }} bs=1M count={{ swap.file_size_mb }}"
  args:
    creates: "{{ swap.file_path }}"
  tags:
    - swap.file.create

- name: Swap | Change swap file permissions
  file:
    path: "{{ swap.file_path }}"
    owner: root
    group: root
    mode: 0600
    state: file
  tags:
    - swap.file.permissions

- name: Swap | Check swap file type
  command: "file {{ swap.file_path }}"
  register: swapfile
  tags:
    - swap.file.mkswap

- name: Swap | Make swap file
  command: "sudo mkswap {{ swap.file_path }}"
  when: swapfile.stdout.find('swap file') == -1
  tags:
    - swap.file.mkswap

- name: Swap | Write swap entry in fstab
  mount:
    name: none
    src: "{{ swap.file_path }}"
    fstype: swap
    opts: sw
    passno: 0
    dump: 0
    state: present
  tags:
    - swap.fstab

- name: Swap | Mount swap
  command: "swapon {{ swap.file_path }}"
  when: ansible_swaptotal_mb < 1
  tags:
    - swap.file.swapon