---
- name: Redis | Add PPA rwky/redis
  sudo: yes
  apt_repository:
    repo: ppa:rwky/redis
    update_cache: yes
    state: present

- name: Redis | Install Redis
  sudo: yes
  apt:
    pkg: redis-server
    update_cache: yes
    cache_valid_time: 3600
    state: latest
  notify: restart redis

- include: phpredis.yml
