---
- name: PHP | Checkout fpm/php.ini file
  stat:
    path: /etc/php/7.0/fpm/php.ini
  register: phpfpm

- name: PHP | Checkout cli/php.ini file
  stat:
    path: /etc/php/7.0/cli/php.ini
  register: phpcli

- include: php-fpm.yml
  when: phpfpm.stat.exists

- include: php-cli.yml
  when: phpcli.stat.exists
