---
- name: Add ppa Repository
  sudo: yes
  apt_repository:
    repo: "ppa:ondrej/{{ php.ppa }}"

- name: Update apt
  sudo: yes
  apt:
    update_cache: yes

- name: Install php7-fpm
  sudo: yes
  apt:
    pkg: php7.0-fpm
    state: latest

- name: Install php7-cli
  sudo: yes
  apt:
    pkg: php7.0-cli
    state: latest

- name: Install PHP Packages
  sudo: yes
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items: php_packages
  when: php_packages is defined

- name: Install xDebug
  sudo: yes
  apt: 
    pkg: php7.0-xdebug
    state: latest
  when: php.xdebug

- include: configure.yml
