---
- name: PHP | Add ppa Repository
  sudo: yes
  apt_repository:
    repo: "ppa:ondrej/{{ php.ppa }}"
    update_cache: yes
    state: present

- name: PHP | Install php7-fpm
  sudo: yes
  apt:
    pkg: php7.0-fpm
    update_cache: yes
    cache_valid_time: 3600
    state: present

- name: PHP | Install php7-cli
  sudo: yes
  apt:
    pkg: php7.0-cli
    update_cache: yes
    cache_valid_time: 3600
    state: present

- name: PHP | Install PHP Packages
  sudo: yes
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  with_items: php_packages
  when: php_packages is defined

- name: PHP | Install xDebug
  sudo: yes
  apt: 
    pkg: php7.0-xdebug
    update_cache: yes
    cache_valid_time: 3600
    state: present
  when: php.xdebug

- include: configure.yml
