---
- name: MongoDB | Add key for MongoDB repository
  sudo: yes
  apt_key:
    keyserver: "hkp://keyserver.ubuntu.com:80"
    id: EA312927

- name: MongoDB | Add MongoDB repository
  sudo: yes
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse"
    state: present
    update_cache: yes

- name: MongoDB | Install MongoDB packages
  sudo: yes
  apt:
    pkg: mongodb-org
    state: present
    update_cache: yes
    cache_valid_time: 3600
  notify: restart mongodb
