---
- name: Nginx | Add PPA nginx/stable
  sudo: yes
  apt_repository:
    repo: ppa:nginx/stable
    update_cache: yes
    state: present

- name: Nginx | Install Nginx
  sudo: yes
  apt:
    pkg: nginx
    update_cache: yes
    cache_valid_time: 3600
    state: present

- name: Nginx | Change default Nginx site
  sudo: yes
  template:
    src: default_nginx.tpl
    dest: /etc/nginx/sites-available/default
  notify: restart nginx

- name: Nginx | Create the log folder
  sudo: yes
  file:
    path: "{{ nginx.log_folder }}"
    owner: www-data
    group: adm
    state: directory

- name: Nginx | Create the access.log
  sudo: yes
  file:
    path: "{{ nginx.log_folder }}/access.log"
    owner: www-data
    group: adm
    state: touch

- name: Nginx | Create the error.log
  sudo: yes
  file:
    path: "{{ nginx.log_folder }}/error.log"
    owner: www-data
    group: adm
    state: touch
